name = "ExperimentalTagbot"
uuid = "930da1f0-8ee6-4872-b248-bb5528d4fa7c"
authors = ["Joey Carpinelli <joey@loopy.codes>"]
version = "0.1.0"

[deps]
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
GitHub = "5.9.0"
